In [1]:
import numpy as np

# creating numpy arrays from python lists

In [2]:
np.array([1,2,4,5,3])

array([1, 2, 4, 5, 3])

In [3]:
#ép kiểu ngầm định
np.array([3.14,4,3,5,6])# các số int sẽ chuyển sang dạng float do 3.14 là float

array([3.14, 4.  , 3.  , 5.  , 6.  ])

In [4]:
#chọn kiểu dử liệu
np.array([17,0,3,25,3], dtype="float32")

array([17.,  0.,  3., 25.,  3.], dtype=float32)

# Creating Arrays from Scratch

## zeros, ones, full, arange, linspace


### ấn shift + tab để hiểu hơn cách dùng

In [8]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create a 3x5 array filled with 3.14
np.full((3,3),3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [16]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## random

In [22]:
np.random.random((2,2))

#OR   np.random.rand(3,5)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [25]:
np.random.seed(0)  # seed for reproducibility
np.random.random((2,2))

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [24]:
np.random.seed(0)  # seed for reproducibility
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))


array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [26]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.86755799, -0.97727788,  0.95008842],
       [-0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773]])

In [27]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[8, 9, 4],
       [3, 0, 3],
       [5, 0, 2]])

## Array Indexing & Slicing

### One-dimensional subarray

In [9]:
x1 = np.random.randint(20, size=6)
print(x1)

[17 14 11  7  5 19]


In [10]:
x1

array([17, 14, 11,  7,  5, 19])

In [13]:
x1[4], x1[1], x1[-1]

(5, 14, 19)

### Multi-dimensional array

In [15]:
x2 = np.random.randint(10, size=(3,4))

In [16]:
x2

array([[3, 0, 6, 7],
       [4, 6, 0, 5],
       [5, 4, 2, 5]])

In [17]:
x2[1,2]

0

In [18]:
x2[1,3] = 3

In [19]:
x2

array([[3, 0, 6, 7],
       [4, 6, 0, 3],
       [5, 4, 2, 5]])

### slicing


### x[start:stop:step]

In [21]:
x1

array([17, 14, 11,  7,  5, 19])

In [22]:
x1[0:3]

array([17, 14, 11])

In [23]:
x1[2:4]

array([11,  7])

In [24]:
x1[::2]

array([17, 11,  5])

In [25]:
x2[:2,:3] # hàng từ 0-2 và cột tử 0-3

array([[3, 0, 6],
       [4, 6, 0]])

## Reshaping of arrays & Transpose

In [29]:
grid = np.arange(1,10)
grid.shape

(9,)

In [30]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
x= np.array([[1,2],[3,4]])


In [32]:
x

array([[1, 2],
       [3, 4]])

In [33]:
x.T  #(là dạng ma trận chuyển vị)

array([[1, 3],
       [2, 4]])

## Array Concatenation and Splitting


In [34]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y]) #axis=0 nối theo hàng không để gì sẽ mặt định

array([1, 2, 3, 3, 2, 1])

In [36]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.concatenate((grid,grid), axis =1 ) # axis=1 nối theo cột

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [38]:
#vstack
x=np.array([1,2,3])

y=np.array([[4,5,6],
            [6,7,8]])

In [39]:
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [41]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([y, grid])

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

### Splitting of arrays

In [2]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


## Manipulating & Comparing Arrays

### Aggregation

In [5]:
list_num = [1,2,3]
ll=np.array(list_num)
ll

array([1, 2, 3])

In [6]:
sum(ll) #Python sum()

6

In [7]:
np.sum(ll) #Numpy sum()

6

In [11]:
# create a masive numpy array

massive_array = np.random.random(1000)

%timeit sum(massive_array) #python built-in funtion sum()

%timeit np.sum(massive_array) #numpy's np.sum()
# => dùng np sử lý nhanh hơn

83.8 µs ± 1.8 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
4.62 µs ± 245 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
np.mean(massive_array) #trung bình

0.5126022910354755

In [14]:
np.max(massive_array)

0.9933186971499958

In [15]:
np.min(massive_array)

0.0036870566721378673

In [19]:
dog_height = [600, 470,170,430,300]
dog_height = np.array(dog_height)

np.std(dog_height) #độ lệch chuẩn

147.32277488562318

In [20]:
np.var(dog_height) #phương sai

21704.0

In [21]:
np.sqrt(np.var(dog_height))

147.32277488562318

## Sorting Arrays
np.sort uses an quicksort algorithm


In [22]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [23]:
#A related function is argsort, which instead returns the indices of the sorted elements:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


## Sorting along rows or columns
NumPy's sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the axis argument

In [25]:
np.random.seed(42)

mat1 = np.random.randint(0,10, size=(4,6))

mat1

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [26]:
np.sort(mat1, axis=0) #sort by column

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [27]:
np.sort(mat1, axis=1) #sort by cow

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

 ## Linear Algebra
(đại số tuyến tính)

In [28]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [29]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [30]:
# A(3x3) dot product B(2X3)
A.dot(B) #nhân 2 ma trận

array([[20, 14],
       [56, 41],
       [92, 68]])

In [31]:
# or
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [32]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### dot product ẽxample

In [33]:
# Number ò jars sold
np.random.seed(0)

sales_amounts = np.random.randint(0,20, size=(5,3))

sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [38]:
# Create weekly_sales DataFrame
import pandas as pd

weekly_sales = pd.DataFrame(sales_amounts, index= ["mon","tues","wed","thurs","fri"],
                                           columns= ["bork","milk","chicken"])

In [36]:
weekly_sales

bork  milk  chicken
mon      12    15        0
tues      3     3        7
wed       9    19       18
thurs     4     6       12
fri       1     6        7

In [43]:
#create a price array
prices = np.array([10,8,12])
prices.shape

(3,)

In [46]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index= ["price"],
                                                  columns= ["bork","milk","chicken"])

In [47]:
butter_prices

bork  milk  chicken
price    10     8       12

In [49]:
weekly_sales.shape, butter_prices.T.shape #kiểm tra để nhân 2 ma trận

((5, 3), (3, 1))

In [51]:
total = weekly_sales.dot(butter_prices.T)
total

price
mon      240
tues     138
wed      458
thurs    232
fri      142

In [54]:
weekly_sales["Total"] = total
weekly_sales

bork  milk  chicken  Total
mon      12    15        0    240
tues      3     3        7    138
wed       9    19       18    458
thurs     4     6       12    232
fri       1     6        7    142