In [120]:
import numpy as np
import pandas as pd

In [121]:
df = pd.read_csv("D:\Downloads\dataset.csv")
df

age   fvc   fev  fvc1  fev1    kg   cm  Label
0      65  2.11  1.68  0.96  0.94  29.0  150      0
1      80  1.56  1.13  0.93  0.49  29.0  145      0
2      53  2.87  2.43  3.05  2.66  30.0  150      0
3      84  1.92  1.37  1.66  1.32  30.0  154      0
4      80  1.91  1.40  0.77  0.42  30.0  152      0
...   ...   ...   ...   ...   ...   ...  ...    ...
2173   36  4.16  3.36  4.09  2.97  95.0  168      0
2174   71  3.38  2.46  2.81  1.85  96.0  170      0
2175   41  4.01  3.20  3.41  2.96  97.0  167      0
2176   71  3.38  2.46  2.98  2.08  98.0  170      0
2177   54  3.72  2.86  2.95  2.25  99.0  167      0

[2178 rows x 8 columns]

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2178 entries, 0 to 2177
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     2178 non-null   int64  
 1   fvc     2178 non-null   float64
 2   fev     2178 non-null   float64
 3   fvc1    2178 non-null   float64
 4   fev1    2178 non-null   float64
 5   kg      2178 non-null   float64
 6   cm      2178 non-null   int64  
 7   Label   2178 non-null   int64  
dtypes: float64(5), int64(3)
memory usage: 136.2 KB


In [123]:
# choose Feature to train ML Model
features = ["age","fvc","fev","fvc1","fev1","kg","cm"]
X = df[features]
X.head(5)

age   fvc   fev  fvc1  fev1    kg   cm
0   65  2.11  1.68  0.96  0.94  29.0  150
1   80  1.56  1.13  0.93  0.49  29.0  145
2   53  2.87  2.43  3.05  2.66  30.0  150
3   84  1.92  1.37  1.66  1.32  30.0  154
4   80  1.91  1.40  0.77  0.42  30.0  152

In [124]:
Y = df["Label"]
Y.head(5)

0    0
1    0
2    0
3    0
4    0
Name: Label, dtype: int64

In [125]:
from sklearn.preprocessing import StandardScaler

# Chuẩn hóa các cột đặc trưng
scaler = StandardScaler()
X = scaler.fit_transform(X)
X

array([[ 0.17701465, -1.35704638, -1.07272978, ..., -1.22402629,
        -2.59782442, -1.47578872],
       [ 1.10602168, -2.19931612, -2.038789  , ..., -1.81421376,
        -2.59782442, -2.17203007],
       [-0.56619097, -0.19318275,  0.24462371, ...,  1.03180137,
        -2.50211082, -1.47578872],
       ...,
       [-1.30939659,  1.55261271,  1.59710663, ...,  1.42525968,
         3.91070036,  0.89143188],
       [ 0.54861746,  0.58783101,  0.29731785, ...,  0.2711153 ,
         4.00641396,  1.30917669],
       [-0.50425717,  1.10850685,  0.99990638, ...,  0.49407501,
         4.10212756,  0.89143188]])

In [126]:
# X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split

X_train, X_valid, Y_train, Y_valid = train_test_split(X,Y, train_size=0.8, test_size=0.2, random_state=0)


In [127]:
X_train.shape # 80%

(1742, 7)

In [128]:
X_valid.shape # 20% còn lại

(436, 7)

In [129]:
df.shape # tổng

(2178, 8)

In [130]:
"""Model này sẽ học cách xây dựng một cây quyết định 
dựa trên các thuộc tính đầu vào của dữ liệu và đầu ra (target) tương ứng với mỗi điểm dữ liệu."""
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor

rf_model = RandomForestRegressor(random_state=1)
#Fit tranining data into model
rf_model.fit(X_train,Y_train)

RandomForestRegressor(random_state=1)

In [131]:
rf_val_preds = rf_model.predict(X_valid)
rf_val_preds

array([0.  , 0.  , 0.  , 0.  , 0.97, 0.  , 0.  , 0.  , 0.08, 0.86, 0.  ,
       0.  , 0.41, 0.  , 0.  , 0.  , 1.  , 0.  , 0.99, 0.  , 0.  , 0.01,
       0.  , 0.21, 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  ,
       0.01, 0.03, 0.05, 0.83, 0.  , 0.  , 0.05, 0.  , 0.  , 0.27, 0.  ,
       0.  , 0.99, 0.  , 0.  , 0.01, 0.  , 0.  , 1.  , 0.  , 0.01, 0.12,
       0.  , 0.01, 0.  , 0.75, 0.01, 0.  , 0.  , 0.  , 0.  , 1.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.44, 0.  , 0.02, 0.  , 0.  ,
       0.  , 1.  , 0.  , 0.21, 0.11, 0.  , 0.01, 0.02, 0.3 , 1.  , 0.  ,
       0.56, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.13,
       0.05, 0.52, 0.  , 0.  , 0.01, 0.94, 0.  , 0.73, 0.02, 0.  , 0.  ,
       0.5 , 0.  , 0.04, 0.  , 0.98, 0.  , 0.76, 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.12, 0.  , 0.  , 0.  , 0.08, 0.  , 0.01, 0.82, 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.06, 0.  , 0.  , 1.  , 0.  , 0.19, 0.01,
       0.85, 0.01, 0.68, 1.  , 0.97, 1.  , 0.  , 0.

In [132]:
rf_val_preds[:5]

array([0.  , 0.  , 0.  , 0.  , 0.97])

In [133]:
rf_model.predict([[65,2.11,1.68,0.96,0.94,29.0,150]])
# lấy hàng đầu tiên nhập vô thử cũng đúng đúng r nè

array([0.])

In [134]:
X_input = []


age = float(input("age: "))
X_input.append(age)

fvc = float(input("fvc: "))
X_input.append(fvc)


fev = float(input("fev: "))
X_input.append(fev)


fvc1 = float(input("fvc1: "))
X_input.append(fvc1)


fev1 = float(input("fev1: "))
X_input.append(fev1)


kg = float(input("kg: "))
X_input.append(kg)


cm = float(input("cm: "))
X_input.append(cm)

# Sử dụng mô hình để dự đoán bệnh
Label = rf_model.predict([X_input])

# Hiển thị kết quả dự đoán 
print("ra gần 0 là không có bệnh còn gần số 1 là có bên á nhe, khúc này tự xử lý đi: {:,.2f}".format(Label[0]))

ra gần 0 là không có bệnh còn gần số 1 là có bên á nhe, khúc này tự xử lý đi: 0.00
